name: animated_radio_buttons
description: A radio button package for flutter.
version: 0.0.3
author: Srihari Ayapilla
homepage: https://github.com/srihariash999/animated_radio_buttons

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

 
